using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using StratFlux.ModelEnums;
using StratFlux.Models;

namespace StratFlux.Data
{
    public class ApplicationDbContext : IdentityDbContext<StratUser>
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {

        }

        // Enum type mappings take place in static constructor because they
        // must be mapped before any entity framework operations take place
        static ApplicationDbContext()
        {
            // Mapping enums to database
            NpgsqlConnection.GlobalTypeMapper.MapEnum<TimeResolution>("Identity.time_resolution");
            NpgsqlConnection.GlobalTypeMapper.MapEnum<CommissionFeeType>("Identity.commission_fee_type");
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            builder.HasDefaultSchema("Identity");

            // All tables created by Identity are renamed with better naming conventions
            builder.Entity<StratUser>(entity => entity.ToTable("TblUsers"));
            builder.Entity<IdentityRole>(entity => entity.ToTable("TblRoles"));
            builder.Entity<IdentityUserRole<string>>(entity => entity.ToTable("TblUserRoles"));
            builder.Entity<IdentityUserClaim<string>>(entity => entity.ToTable("TblUserClaims"));
            builder.Entity<IdentityUserLogin<string>>(entity => entity.ToTable("TblUserLogins"));
            builder.Entity<IdentityRoleClaim<string>>(entity => entity.ToTable("TblRoleClaims"));
            builder.Entity<IdentityUserToken<string>>(entity => entity.ToTable("TblUserTokens"));
            builder.Entity<BacktestingSettings>(entity => entity.ToTable("TblBacktestingSettings"));
            builder.Entity<Strategy>(entity => entity.ToTable("TblStrategies"));
            builder.Entity<GeneralResults>(entity => entity.ToTable("TblGeneralResults"));
            builder.Entity<Chart>(entity => entity.ToTable("TblCharts"));
            builder.Entity<Indicator>(entity => entity.ToTable("TblIndicators"));
            builder.Entity<ChartIndicatorMapping>(entity => entity.ToTable("TblChartIndicatorMappings"));
            builder.Entity<TimeSeriesData>(entity => entity.ToTable("TblTimeSeriesData"));
            builder.Entity<FriendList>(entity => entity.ToTable("TblFriendList"));
            builder.Entity<MessageHistory>(entity => entity.ToTable("TblMessageHistory"));

            // All new tables need to have their keys auto-generated by the table. I must manually specify this for each table in the context like so:
            builder.Entity<BacktestingSettings>().Property(entity => entity.Id).ValueGeneratedOnAdd();
            builder.Entity<Strategy>().Property(entity => entity.Id).ValueGeneratedOnAdd();
            builder.Entity<GeneralResults>().Property(entity => entity.Id).ValueGeneratedOnAdd();
            builder.Entity<Chart>().Property(entity => entity.Id).ValueGeneratedOnAdd();
            builder.Entity<Indicator>().Property(entity => entity.Id).ValueGeneratedOnAdd();
            builder.Entity<ChartIndicatorMapping>().Property(entity => entity.Id).ValueGeneratedOnAdd();
            builder.Entity<TimeSeriesData>().Property(entity => entity.Id).ValueGeneratedOnAdd();
            builder.Entity<FriendList>().Property(entity => entity.Id).ValueGeneratedOnAdd();
            builder.Entity<MessageHistory>().Property(entity => entity.Id).ValueGeneratedOnAdd();

            // Here, I map some custom enums to the database so they can be used in selection fields
            builder.HasPostgresEnum<TimeResolution>(schema: "Identity");
            builder.HasPostgresEnum<CommissionFeeType>(schema: "Identity");

            // Here, some additional attributes are added to columns given by Identity

            // Max and Min Length for username which was previously given by Identity is adjusted
            builder.Entity<StratUser>().Property(entity => entity.UserName)
                .HasMaxLength(15)
                .HasAnnotation("MinLength", 3)
                .IsRequired();

            // Same for normalised username
            builder.Entity<StratUser>().Property(entity => entity.NormalizedUserName)
                .HasMaxLength(15)
                .HasAnnotation("MinLength", 3);
        }

        public DbSet<StratFlux.Models.BacktestingSettings>? BacktestingSettings { get; set; }
        public DbSet<StratFlux.Models.Strategy>? Strategies { get; set; }
        public DbSet<StratFlux.Models.GeneralResults>? GeneralResults { get; set; }
    }
}